Repository AlpsBTE/alpsbte-website, pull requests merged in 2021-09, with the labels that each got.

#85 68 loading page
  libs/loader/src/lib/loader.module.scss
  libs/loader/src/lib/loader.scss
  libs/loader/src/lib/loader.tsx
Labels: frontend

#106 Fixed netlify routing issue
  apps/alpsbte-web/src/_redirects
Labels: bug

#109 Added language select on mobile version
  libs/shared/components/src/lib/header/header.tsx
Labels: bug, frontend, design

#110 added meta tags
  apps/alpsbte-web/src/index.html
Labels: enhancement

#111 Navbar style correction
  libs/shared/components/src/lib/header/header.scss
  libs/shared/theme/src/lib/variables/index.scss
Labels: frontend

#118 Link social media icons
  libs/contact/src/lib/contact.tsx
Labels: frontend

#129 128 fix spacings on home page
  libs/contact/src/lib/contact.scss
  libs/home/src/components/home-content-section/home-content-section.scss
  libs/shared/components/src/lib/footer/footer.scss
  libs/shared/components/src/lib/header/header.scss
  libs/shared/components/src/lib/language-select/language-select.scss
  libs/shared/config/src/lib/breakpoints.ts
Labels: frontend
